[package]
name = "blockchain_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] } # Optional for CLI interactivity
